name: cgpa_cal
description: Calculate your CGPA

publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.14.1
  shared_preferences: ^2.2.2
  marquee: ^2.2.3
  provider: ^6.1.1
  collection: ^1.17.2
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  google_sign_in: ^6.1.6
  page_transition: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.13.0
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold/ttf
          weight: 700

    - family: noto
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
