// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY83ViA1Nri876n26WKLBIs6iDk6i1Kmg',
    appId: '1:110794984018:web:b3129b41f93e529545ad8b',
    messagingSenderId: '110794984018',
    projectId: 'cgpa-calculator-st',
    authDomain: 'cgpa-calculator-st.firebaseapp.com',
    storageBucket: 'cgpa-calculator-st.appspot.com',
    measurementId: 'G-45CY1DC04K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNBXRpllWzsMHjexItt1nn_McIQPdOdA',
    appId: '1:110794984018:android:b8c50555aba132a345ad8b',
    messagingSenderId: '110794984018',
    projectId: 'cgpa-calculator-st',
    storageBucket: 'cgpa-calculator-st.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGlhGVwy2t7W8o2pckbiwzxBeRoNGsxM',
    appId: '1:110794984018:ios:8c901a541ed8803945ad8b',
    messagingSenderId: '110794984018',
    projectId: 'cgpa-calculator-st',
    storageBucket: 'cgpa-calculator-st.appspot.com',
    iosBundleId: 'com.sasanktumpati.cgpaCal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrGlhGVwy2t7W8o2pckbiwzxBeRoNGsxM',
    appId: '1:110794984018:ios:5c68c59ce95c1c0c45ad8b',
    messagingSenderId: '110794984018',
    projectId: 'cgpa-calculator-st',
    storageBucket: 'cgpa-calculator-st.appspot.com',
    iosBundleId: 'com.sasanktumpati.cgpaCal.RunnerTests',
  );
}
